name: Benchmarks
on:
  workflow_dispatch:

jobs:
  jvme:
    strategy:
      matrix:
        version: ['8', '17', '21']
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: ${{ matrix.version }}
          distribution: 'liberica'
          #architecture: x64

      - name: Run benchmarks
        run: ./gradlew jvmBenchmark -PjvmVersion=${{matrix.version}}

      - name: Copy results
        run: |
          REPORTS_DIR=build/reports/benchmarks/main
          DIR_NAME=$(ls $REPORTS_DIR | head -n1)
          mkdir -p results
          ls $REPORTS_DIR/$DIR_NAME/*.json | while read report_json; do cp $report_json results/$DIR_NAME-${{matrix.os}}-jdk${{matrix.version}}.json; done

      - name: Publish results
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TOKEN }}
          add-paths: results/*.json
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: results-${{ github.job }}
          title: 'Benchmarking report'
